email:
  sent_from : "mayug.vaccine@gmail.com" 
  email_password : "iit2013jee"

  # [edit] enter receiver email details
  to : ["mayug.vaccine@gmail.com"]

area_info:
# [edit] enter your district code or pincode
  __district_code : "302,303,307,305" 
  __pincode : "<pincode>"
  
age_limit:
  age_limit : [18]
